trinitystore/payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/stripe', webhooks.stripe_webhook, name='stripe-webhook'),
    path('webhook/paypal', webhooks.paypal_webhook, name='paypal-webhook'),
]

trinitystore/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('shop/', views.product_list1, name='product_list1'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_slug'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

trinitystore/trinitystore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls', namespace='account')),
                  path('first/', include('firstpage.urls', namespace='firstpage')),
                  path('social-auth', include('social_django.urls', namespace='social')),
                  path('order/', include('order.urls', namespace='order')),
                  path('payment/', include('payment.urls', namespace='payment')),
                  path('store/', include('shop.urls', namespace='shop')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trinitystore/payment/models.py
from django.db import models

# Create your models here.

trinitystore/payment/views.py
from decimal import Decimal

import stripe
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from order.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }
        session_data['line_items'].append({
            'price_data': {
                'unit_amount': int(order.item.price * Decimal('100')),
                'currency': 'usd',
                'product_data': {
                    'name': order.item.name,
                },
            },
            'quantity': 1
        })
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code=303)


def payment_completed(request):
    return render(request, 'payment/completed.html')


def payment_canceled(request):
    return render(request, 'payment/canceled.html')


trinitystore/templates/payment/canceled.html
{% extends "shop/base.html" %}

{% block title %}Payment canceled{% endblock %}

{% block content %}
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
{% endblock %}

trinitystore/templates/payment/completed.html
{% extends "base_shop.html" %}

{% block title %}Payment successful{% endblock %}

{% block content %}
    <h1>Your payment was successful</h1>
    <p>Your payment has been processed successfully.</p>
{% endblock %}

trinitystore/templates/payment/process.html
{% extends "base_shop.html" %}
{% load static %}

{% block title %}Pay your order{% endblock %}

{% block content %}
    <h1>Order summary</h1>
    <table class="cart">
        <thead>
            <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class="row{% cycle "1" "2" %}">
                    <td>
                        <img src="{% if item.product.image %}{{ item.product.image.url }}
                        {% else %}{% static "img/no_image.png" %}{% endif %}">
                    </td>
                    <td>{{ item.product.name }}</td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">{{ item.quantity }}</td>
                    <td class="num">${{ item.get_cost }}</td>
                </tr>
            {% endfor %}
            <tr class="total">
                <td colspan="4">Total</td>
                <td class="num">${{ order.get_total_cost }}</td>
            </tr>
        </tbody>
    </table>
    <form action="{% url "payment:process" %}" method="post">
        <input type="submit" value="Pay now">
        {% csrf_token %}
    </form>
{% endblock %}