trinitystore/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.create_order, name='create_order')
]

trinitystore/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('shop/', views.product_list1, name='product_list1'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_slug'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

trinitystore/trinitystore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls', namespace='account')),
                  path('first/', include('firstpage.urls', namespace='firstpage')),
                  path('social-auth', include('social_django.urls', namespace='social')),
                  path('order/', include('order.urls', namespace='order')),
                  path('payment/', include('payment.urls', namespace='payment')),
                  path('store/', include('shop.urls', namespace='shop')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trinitystore/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_slug', args=[self.slug])


class Product(models.Model):
    VIP_TYPES = (
        ('MONTH', 'Month'),
        ('3MONTH', '3Month'),
        ('LIFETIME', 'Lifetime'),
        ('1YEAR', '1year')
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=200)
    plan_type = models.CharField(max_length=16, choices=VIP_TYPES, default='Month')
    slug = models.CharField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

trinitystore/shop/forms.py
from django import forms
from .models import Product


# class ChoiceProduct(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = ('name',)
#         widgets = {
#             'name' :
#         }


class ChoiceProduct(forms.Form):
    pass

trinitystore/shop/views.py
from django.shortcuts import render, get_object_or_404

from .forms import ChoiceProduct
from .models import Category, Product


# def product_list(request, category_slug=None):
#     categories = Category.objects.all()
#     products = Product.objects.filter(available=True)
#     category = None
#     if category_slug:
#         category = get_object_or_404(
#             Category, slug=category_slug
#         )
#         products = products.filter(category=category)
#     return render(request,
#                   'shop/product/list.html',
#                   {'category': category,
#                    'products': products,
#                    'categories': categories})

# def product_list(request):
#     form = ChoiceProduct()
#     return render(request, 'shop/product/list2.html', {'form': form})

def product_list(request):
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/shop.html', {'products': products,
                                                      'section': 'shop'})


def product_list1(request):
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/list3.html', {'products': products,
                                                      'section': 'shop'})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    return render(request, 'shop/product/detail.html', {'product': product})

trinitystore/templates/shop/product/detail.html
{% extends "base_shop.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "shop/img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">${{ product.price }}</p>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

trinitystore/templates/shop/product/list.html
{% extends "base_shop.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"
                {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products
        {% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}
                    {% static "shop/img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

trinitystore/templates/shop/product/list2.html
{% extends "base_shop.html" %}
{% load static %}

{% block content %}
  <form method="post">
    {{ form.as_p }}
    <p><input type="submit" value="Change"></p>
    {% csrf_token %}
  </form>
{% endblock %}

trinitystore/templates/shop/product/list3.html
{% extends "base_shop.html" %}
{% load static %}

{% block content %}
  <div id="main" class="product-list">
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}
                    {% static "shop/img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                ${{ product.price }}
                <br>
                <form action="{% url "order:create_order" %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="plan" value="{{ product.plan_type }}">
                    <input type="submit" value="Buy">
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}

trinitystore/templates/shop/product/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Dashboard 3</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'Adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- IonIcons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' }">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'Adminlte/dist/css/adminlte.min.css' %}">
  <!-- CSS only -->
<!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">-->
<!--  django 4 css from github-->
<!--  <link href="{% static "shop/css/base.css" %}" rel="stylesheet">-->
</head>
<!--
`body` tag options:

  Apply one or more of the following classes to to the body tag
  to get the desired effect

  * sidebar-collapse
  * sidebar-mini
-->
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="../../account/index3.html" class="brand-link text-center" style="width: 150px">
          <img src="{% static 'Adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
          <span class="brand-text font-weight-light">Trinity</span>
        </a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>-->
<!--      </li>-->
<!--      <li class="nav-item d-none d-sm-inline-block">-->
<!--        <a href="index3.html" class="nav-link">Trinity</a>-->
<!--      </li>-->
<!--      <li class="nav-item d-none d-sm-inline-block">-->
<!--        <a href="#" class="nav-link">Contact</a>-->
<!--      </li>-->
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">-->
<!--          <i class="fas fa-th-large"></i>-->
<!--        </a>-->
<!--      </li>-->
    </ul>
  </nav>
  <!-- /.navbar -->
<!--    <nav class="navbar navbar-expand-lg navbar-light sticky-top bg-white p-2 shadow" style="&#45;&#45;bs-bg-opacity: 0.75" data-darkreader-inline-bgcolor="">-->
<!--        <div class="container">-->
<!--            <a class="navbar-brand" href="#">Web developers</a>-->
<!--            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">-->
<!--                <span class="navbar-toggler-icon"></span>-->
<!--            </button>-->

<!--            <div class="collapse navbar-collapse" id="navbarColor03">-->
<!--                <ul class="navbar-nav mx-auto">-->
<!--                <li class="nav-item active">-->
<!--                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Features</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Pricing</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">About</a>-->
<!--                </li>-->
<!--                </ul>-->
<!--                <div class="form-inline justify-content-end" style="width: 154px;">-->
<!--                <button class="btn btn-primary">Get started!</button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </nav>-->

  {% include 'account/sidebar.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Store</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">User Profile</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">

          {% for product in products %}

          <div class="col-md-4 item" style="text-align: center; ">
              <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}{% else %}
                  {% static 'shop/img/no_image.png' %}{% endif %}" style="width: 90%; font-family: helvetica, sans-serif;">
              </a>
              <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
              <br>
              ${{ product.price }}
              <br>
              <form action="{% url "order:create_order" %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="plan" value="{{ product.plan_type }}">
                  <input type="submit" value="Buy" style="color: #fff;
                                                          background: #5993bb;
                                                          border-radius: 1px;
                                                          padding: 10px 20px;
                                                          font-size: 16px;
                                                          border: 0;">
              </form>
          </div>
          {% endfor %}


        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
  </div>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://trinity">Trinity</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'Adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'Adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<!-- AdminLTE -->
<script src="{% static 'Adminlte/dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'Adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<!--<script src="{% static 'Adminlte/dist/js/demo.js' %}"></script>-->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'Adminlte/dist/js/pages/dashboard3.js' %}"></script>
</body>
</html>