trinitystore/account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from account import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password-reset/',
         views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

    # path('', include('django.contrib.auth.urls')),
    path('', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('edit/', views.do_edit, name='do-edit'),
    path('post/ajax/friend', views.edit, name='edit'),
    path('vip/', views.vip, name='vip'),
    path('vip/download/', views.download, name='file_download')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trinitystore/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('shop/', views.product_list1, name='product_list1'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_slug'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

trinitystore/trinitystore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include('account.urls', namespace='account')),
                  path('first/', include('firstpage.urls', namespace='firstpage')),
                  path('social-auth', include('social_django.urls', namespace='social')),
                  path('order/', include('order.urls', namespace='order')),
                  path('payment/', include('payment.urls', namespace='payment')),
                  path('store/', include('shop.urls', namespace='shop')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trinitystore/templates/base_blog.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>
            This is my blog.
            I've written {% total_posts %} posts.
        </p>
        <h3>latest posts</h3>
        {% get_latest_posts 3 %}
        <h3>Most commented posts</h3>
        {% get_most_commented_post as most_commented_post %}
        <ul>
            {% for post in most_commented_post %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

trinitystore/templates/base_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'account/css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <span class="logo">Trinity</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %} class='selected' {% endif %}>
                    <a href="{% url 'account:dashboard' %}">My dashboard</a>
                </li>
                <li {% if section == 'shop' %} class='selected'{% endif %}>
                    <a href="{% url 'shop:product_list' %}">Shop</a>
                </li>
                <li {% if section == 'forum' %} class="selected" {% endif %}>
                    <a href="{% url 'blog:post_list' %}">Forum</a>
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name|default:request.user.username }}
                <a href="{% url 'account:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'account:login' %}">Login</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags}}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<!--    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>-->
    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

trinitystore/templates/base_shop.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "shop/css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            Your cart is empty.
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

trinitystore/templates/login.html
{% extends 'base_registration.html' %}

{% block title %}Log-In{% endblock %}

{% block content %}
  <h1> Log In </h1>
  {% if form.errors %}
    <p>
      Your username and password didn't match.
      Please try again.
    </p>
  {% else %}
    <p>
      Please, use the following form to log-in.
      If you don't have an account <a href="{% url "account:register" %}">register here</a>.
    </p>
  {% endif %}
  <div class="login-form">
    <form action="{% url 'account:login' %}" method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">
      <input type="submit" value="login">
    </form>
    <p>
      <a href="{% url "account:password_reset" %}">
      Forgotten your password?
      </a>
    </p>
  </div>
{% endblock %}

trinitystore/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>